apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hsm

resources:
  - namespace.yaml
  - backend-config.yaml
  - backend-secret.yaml
  - backend-serviceaccount.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-ingress.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - backend-networkpolicy.yaml

