apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: hsm-backend-config
    patch: |-
      - op: replace
        path: /data/ENV
        value: staging
      - op: replace
        path: /data/CORS_ORIGINS
        value: "https://staging.example.com"
  - target:
      kind: Ingress
      name: hsm-backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api-staging.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api-staging.example.com

