// Round-15 Sprint 15m — auto-generated by openapi-typescript.
//
// This file is the SKELETON / placeholder. It will be overwritten by
// the first successful run of `npm run gen:api-types` once
// `openapi-typescript` is installed in CI.
//
// DO NOT edit by hand. Run `npm run gen:api-types` after backend
// schema changes. CI gates this with `npm run gen:api-types:check`.
//
// Migration plan: `docs/audits/2026-05-19-15m-openapi-typescript-adoption.md`.
//
// While the placeholder is in place, the hand-written types in
// `frontend/src/lib/types.ts` remain the source of truth for the SPA.

export type paths = Record<string, never>;
export type components = {
  schemas: Record<string, never>;
};
export type operations = Record<string, never>;
